/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmapTransformer;

public class App {

    public static void main(String[] args) {
        // gather user input
        // store CLI arguments in variables
        String infile = args[0];
        String outfile = args[1];
        String transform = args[2];

        // instantiate bitmap class
        new Bitmap(infile, outfile, transform);
        // run transform method
    }
}
